### PR TITLE
Use more robust raw string quoting

### LINKED ISSUE #1097: `e.json` does not handle strings with literal `$$`.
Creating a JSON literal with `e.json` wraps your string in `$$` to handle multiline strings, as noted in the docs:

```edgeql
select $$one
two
three$$; # multiline raw string
```
- https://docs.edgedb.com/database/edgeql/literals#strings

Here's an example of a failing query:

```ts
    const data = [{ title: "Black Widow $$$*", genre: "Action", rating: 5 }];
    const q2 = e.for(e.json_array_unpack(e.json(data)), (j) =>
      e.insert(e.Movie, {
        title: e.cast(e.str, e.json_get(j, "title")),
        genre: e.cast(e.Genre, e.json_get(j, "genre")),
        rating: e.cast(e.int16, e.json_get(j, "rating")),
      }),
    );
```

Generates:

```edgeql
    FOR __forVar__0 IN {std::json_array_unpack(to_json($$[{"title":"Black Widow $$$*","genre":"Action","rating":5}]$$))}
    UNION (
      (INSERT default::Movie {
        title := (<std::str>std::json_get(__forVar__0, "title")),
        genre := (<default::Genre>std::json_get(__forVar__0, "genre")),
        rating := (<std::int16>std::json_get(__forVar__0, "rating"))
      })
    )
```

Gives you the following runtime error:

> EdgeQLSyntaxError: bare $ is not allowed

### PR DESCRIPTION
**Pull request by scotttrinh**
Input data is likely to contain the string `"$$"`, so use an interstitial label to make it less likely to collide with typical JSON data.

Closes #1097

### CODE REVIEW

File: packages/generate/src/syntax/toEdgeQL.ts [hunk 1]
```diff
@@ -1454,7 +1454,21 @@ function literalToEdgeQL(type: BaseType, val: any): string {
   let stringRep;
   if (typename === "std::json") {
     skipCast = true;
-    stringRep = `to_json($$${JSON.stringify(val)}$$)`;
+    const stringified = JSON.stringify(val);
+    const buildLabel = (
+      dataStr: string,
+      currentLabel: string = "jsonliteral",
+    ) => {
+      if (dataStr.includes(`$${currentLabel}$`)) {
```
Comment (1st1) [inline packages/generate/src/syntax/toEdgeQL.ts:1462]: can you replace this with while?

Comment (1st1) [reply packages/generate/src/syntax/toEdgeQL.ts:1462]: and just error out if we fail to find a unique quote string after a few iterations

Comment (1st1) [reply packages/generate/src/syntax/toEdgeQL.ts:1462]: i'd also replace random chars with just a sequence of random digits to make it less lucrative for someone to guess or try to anything funny

File: packages/generate/src/syntax/toEdgeQL.ts [hunk 2]
```diff
@@ -1448,13 +1448,29 @@ const numericalTypes: Record<string, boolean> = {
...
 
+function makeLabel(stringified: string): string {
+  const MAX_ITERATIONS = 100;
+  let label = `jsonliteral`;
+  let counter = 0;
+  while (stringified.includes(`$${label}$`) && counter < MAX_ITERATIONS) {
+    label = `${label}${counter}`;
+    counter++;
+  }
+  if (counter === MAX_ITERATIONS) {
```
Comment (1st1) [inline packages/generate/src/syntax/toEdgeQL.ts:1459]: just easier to read / reason

```suggestion
  if (counter >= MAX_ITERATIONS) {
```

**Review by 1st1 — APPROVED** [review]

**Review by 1st1 — COMMENTED** [review]
looks good but add a contrived test to check it erroring out. that's important to prevent accidental regression. This is security critical code.

File: packages/generate/src/syntax/toEdgeQL.ts [hunk 3]
```diff
@@ -1448,13 +1449,34 @@ const numericalTypes: Record<string, boolean> = {
...
 function literalToEdgeQL(type: BaseType, val: any): string {
   const typename = (type as any).__casttype__?.__name__ ?? type.__name__;
   let skipCast = false;
   let stringRep;
   if (typename === "std::json") {
     skipCast = true;
-    stringRep = `to_json($$${JSON.stringify(val)}$$)`;
+    const stringified = JSON.stringify(val);
+    const label = `$${makeLabel(stringified)}$`;
+    stringRep = `to_json(${label}${JSON.stringify(val)}${label})`;
```
Comment (CarsonF) [inline packages/generate/src/syntax/toEdgeQL.ts:1479]:
```suggestion
    stringRep = `to_json(${label}${stringified}${label})`;
```

Comment (scotttrinh) [reply packages/generate/src/syntax/toEdgeQL.ts:1479]: oop, nice catch of the refactor miss. will fix!
