### PR TITLE
Fix querybuilder generated query when using unpathed scoped expr

### LINKED ISSUE #808: Query builder builds broken query
**Code**
The code causing the error.

```typescript
import {createClient} from 'edgedb';
import e from './dbschema/edgeql-js';

const client = createClient({});

async function run() {
  const query = e.select(
    e.select(e.Movie, (movie) => ({
      filter: e.op(movie.id, '=', e.uuid('1f406dd0-f1c7-11ed-ab80-d32f12dd164e'))
    })),
    (movie) => ({
      comp: e.op('exists', movie.is(e.Movie))
    }),
  );

  console.log(query.toEdgeQL());
  const result = await query.run(client);
}

run();
```

**Schema**

From edgedb/edgedb-movies

**Generated EdgeQL**

```
WITH
  __withVar_2 := (__scope_1_defaultMovie.id = <std::uuid>"1f406dd0-f1c7-11ed-ab80-d32f12dd164e"),
  __scope_0_defaultMovie := (
    WITH
      __scope_1_defaultMovie := DETACHED default::Movie
    SELECT __scope_1_defaultMovie {
      id
    }
    FILTER __withVar_2
  )
SELECT __scope_0_defaultMovie {
  single comp := (exists (__scope_0_defaultMovie {id})[IS default::Movie])
}
```

**Error or desired behavior**

```
InvalidReferenceError: object type or alias 'default::__scope_1_defaultMovie' does not exist
   |
 2 |   __withVar_2 := (__scope_1_defaultMovie.id = <std::uuid>"1f406dd0-f1c7-11ed-ab80-d32f12dd164e"),
   |                   ^^^^^^^^^^^^^^^^^^^^^^

```

**Versions (please complete the following information):**

- `edgedb-js` version (e.g. `1.4.1`;):
- `@edgedb/generate` version (e.g. `0.4.1`;):

### PR DESCRIPTION
**Pull request by jaclarke**
Fixes #808

When walking the expr tree the scoped copy of a select/update expr passed to the shape should have been treated as an opaque reference and not walked, since it will get walked again by the enclosing select/update.

Currently we are only checking this in path expressions (eg. `movie.title`) and not when the scoped expr appears anywhere else (eg. `movie.is(e.Movie)`). And since the expr is getting walked multiple times, it's messing up the ref counting, and exprs are getting hoisted when they shouldn't, causing the broken queries in #808.

### CODE REVIEW

File: packages/generate/src/syntax/toEdgeQL.ts [hunk 1]
```diff
@@ -473,16 +480,9 @@ function walkExprTree(
     case ExpressionKind.PathLeaf:
     case ExpressionKind.PathNode:
       if (expr.__parent__) {
-        if ((expr.__parent__.type as any).__scopedFrom__) {
```
Comment (scotttrinh) [inline packages/generate/src/syntax/toEdgeQL.ts:476]: Are we losing this special check or is the `expr.__scopedFrom__` going to catch the same things that this `expr.__parent__.type.__scopedFrom__` check is looking for?

Comment (jaclarke) [reply packages/generate/src/syntax/toEdgeQL.ts:476]: Yes, the scoped expr check for `expr.__parent__.type` is now just inside the `walkExprTree` call, so it also catches the scoped exprs wherever they're used, and not just in paths.

Comment (scotttrinh) [reply packages/generate/src/syntax/toEdgeQL.ts:476]: ahh, that makes sense 👍

**Review by scotttrinh — APPROVED** [review]
Glorious.
