### PR TITLE
Only use SNI if servername is not an IP address

### LINKED ISSUE #789: Setting the TLS ServerName to an IP address is not permitted by RFC 6066
**Describe the bug**
DSN: `edgedb://USER:PASSWORD@127.0.0.1:10703/dev_faundr_ru`
```
(node:104660) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
    at Object.connect (node:_tls_wrap:1796:15)
    at RawConnection.newSock (/nix/store/9byc3kizaqqq3x3v1367ffppyqqfi9z1-dev_faundr_ru/api/node_modules/.pnpm/edgedb@1.4.1/node_modules/edgedb/dist/rawConn.js:202:35)
    at RawConnection.connectWithTimeout (/nix/store/9byc3kizaqqq3x3v1367ffppyqqfi9z1-dev_faundr_ru/api/node_modules/.pnpm/edgedb@1.4.1/node_modules/edgedb/dist/rawConn.js:217:27)
    at retryingConnect (/nix/store/9byc3kizaqqq3x3v1367ffppyqqfi9z1-dev_faundr_ru/api/node_modules/.pnpm/edgedb@1.4.1/node_modules/edgedb/dist/retry.js:53:26)
    at ClientPool.getNewConnection (/nix/store/9byc3kizaqqq3x3v1367ffppyqqfi9z1-dev_faundr_ru/api/node_modules/.pnpm/edgedb@1.4.1/node_modules/edgedb/dist/baseClient.js:348:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ClientConnectionHolder._getConnection (/nix/store/9byc3kizaqqq3x3v1367ffppyqqfi9z1-dev_faundr_ru/api/node_modules/.pnpm/edgedb@1.4.1/node_modules/edgedb/dist/baseClient.js:93:32)
    at async ClientConnectionHolder.retryingFetch (/nix/store/9byc3kizaqqq3x3v1367ffppyqqfi9z1-dev_faundr_ru/api/node_modules/.pnpm/edgedb@1.4.1/node_modules/edgedb/dist/baseClient.js:180:26)
    at async Client.execute (/nix/store/9byc3kizaqqq3x3v1367ffppyqqfi9z1-dev_faundr_ru/api/node_modules/.pnpm/edgedb@1.4.1/node_modules/edgedb/dist/baseClient.js:482:20)
```

**Expected behavior**
Do not use deprecation methods warning

**Versions (please complete the following information):**

- OS: Linux 6.6.2-arch1-1
- EdgeDB version (e.g. `2.0`): 4.1
- EdgeDB CLI version (e.g. `2.0`): 4.1.0-dev
- `edgedb-js` version (e.g. `0.20.10`;): 1.4.1 
- Node/Deno version: Node v21.2.0

### PR DESCRIPTION
**Pull request by scotttrinh**
Closes #789 

Per @aljazerzen great explanation:

> If they are using an IP in the URL, they mean to "connect to the machine at this IP", but if they are using a domain name, they mean to "connect to the machine at IP that this domain resolves to and then pick the correct server out of possibly many edgedb-servers running on that machine"

### CODE REVIEW

File: packages/driver/src/rawConn.ts [hunk 1]
```diff
@@ -53,12 +53,15 @@ function getTlsOptions(config: ResolvedConnectConfig): tls.ConnectionOptions {
 
   const tlsOptions: tls.ConnectionOptions = {
     ALPNProtocols: ["edgedb-binary"],
-    // XXX Deno doesn't support this and that means it won't
-    // work with EdgeDB Cloud.
-    servername: config.address[0],
     rejectUnauthorized: tlsSecurity !== "insecure",
   };
 
+  if (net.isIP(config.address[0]) !== 0) {
```
Comment (aljazerzen) [inline packages/driver/src/rawConn.ts:59]: If it is an IP, `isIP` will return 4 or 6, so this condition will be true, so we will set the `servername`.

I think this should be backwards. We should set the `servername` when this is not an IP.

Comment (scotttrinh) [reply packages/driver/src/rawConn.ts:59]: Oh, right 🤦 . I'll make a boolean variable so this is more obvious.
